optimizely/java-sdk

core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilder.java
@aliabbasrizvi @haleybash-optimizely @delikat
=> Change revenue to eventValue

core-httpclient-impl/src/main/java/com/optimizely/ab/event/AsyncEventHandler.java
@aliabbasrizvi @haleybash-optimizely @delikat
=> Remove extraneous log

core-api/src/main/java/com/optimizely/ab/config/Attribute.java, core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java, core-api/src/main/java/com/optimizely/ab/config/parser/JacksonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigGsonDeserializer.java, core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigJacksonDeserializer.java, core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java, core-api/src/test/resources/config/no-audience-project-config-v2.json, core-api/src/test/resources/config/valid-project-config-v2.json
@aliabbasrizvi @delikat @haleybash-optimizely
=> Add support for attributes key in datafile, while maintaining backwards compatibility for dimensions

core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/internal/ProjectValidationUtils.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV1.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java, core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java, core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV1Test.java, core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java, core-api/src/test/java/com/optimizely/ab/internal/ProjectValidationUtilsTestV1.java, core-api/src/test/java/com/optimizely/ab/internal/ProjectValidationUtilsTestV2.java, core-api/src/test/resources/config/valid-project-config-v1.json, core-api/src/test/resources/config/valid-project-config-v2.json
@aliabbasrizvi @haleybash-optimizely @delikat @jophde
=> Give precedence to whitelisting over audience evaluation

core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/config/parser/ConfigParseException.java, core-api/src/main/java/com/optimizely/ab/config/parser/GsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JacksonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java, core-api/src/main/java/com/optimizely/ab/event/EventHandler.java, core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV1.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java
- Checked exception thrown by builder if datafile is invalid
- Exceptions thrown by event dispatcher are gracefully handled
@haleybash-optimizely @aliabbasrizvi @delikat @jophde
=> Add exception handling for datafile parsing and event dispatcher

CONTRIBUTING.md
@haleybash-optimizely @aliabbasrizvi @delikat
=> Add CLA to contributing section

README.md
=> fix developer docs link

CHANGELOG.md, gradle.properties
=> Update CHANGELOG and bump version

CHANGELOG.md, gradle.properties
=> Release version 1.0.1

core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV1.java, core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV1Test.java
=> Remove ppid query string from v1 events

CHANGELOG.md
=> Update changelog to include ppid removal

CHANGELOG.md, core-api/src/main/java/com/optimizely/ab/config/parser/GsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JacksonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java, core-api/src/test/java/com/optimizely/ab/config/parser/GsonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JacksonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JsonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JsonSimpleConfigParserTest.java, gradle.properties
=> Gracefully handle datafile that doesn't contain required fields

CHANGELOG.md, core-api/src/main/java/com/optimizely/ab/config/parser/GsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JacksonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java, core-api/src/test/java/com/optimizely/ab/config/parser/GsonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JacksonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JsonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JsonSimpleConfigParserTest.java, gradle.properties
=> Release version 1.0.2

core-httpclient-impl/src/main/java/com/optimizely/ab/event/AsyncEventHandler.java
This was re-introduced in my `EventBuilderV2` changes.
=> Remove re-introduced extraneous log

core-api/build.gradle
=> Add jackson-annotations as a compile dependency

gradle.properties
=> Bump version to 1.0.3

core-api/build.gradle, core-httpclient-impl/src/main/java/com/optimizely/ab/event/AsyncEventHandler.java, gradle.properties
=> Release version 1.0.3

core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/UnknownLiveVariableException.java, core-api/src/main/java/com/optimizely/ab/config/LiveVariable.java, core-api/src/main/java/com/optimizely/ab/config/LiveVariableUsageInstance.java, core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java, core-api/src/main/java/com/optimizely/ab/config/ProjectConfigUtils.java, core-api/src/main/java/com/optimizely/ab/config/Variation.java, core-api/src/main/java/com/optimizely/ab/config/parser/ExperimentGsonDeserializer.java, core-api/src/main/java/com/optimizely/ab/config/parser/GroupGsonDeserializer.java, core-api/src/main/java/com/optimizely/ab/config/parser/GsonHelpers.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigGsonDeserializer.java, core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigJacksonDeserializer.java, core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV3.java, core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTest.java, core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java, core-api/src/test/java/com/optimizely/ab/config/parser/GsonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JacksonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JsonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JsonSimpleConfigParserTest.java, core-api/src/test/resources/config/no-audience-project-config-v3.json, core-api/src/test/resources/config/valid-project-config-v3.json
- Add parsing logic for live variable entities
- Add public getters for live variable values
=> Add live variables

CHANGELOG.md, gradle.properties
=> Release 1.1.0

CHANGELOG.md, core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/bucketing/Bucketer.java, core-api/src/main/java/com/optimizely/ab/bucketing/UserExperimentRecord.java, core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV1.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV3.java, core-api/src/test/java/com/optimizely/ab/bucketing/BucketerTest.java
=> Revert "Merge pull request #35 from optimizely/mng/rename-user-profile"

CHANGELOG.md, core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/bucketing/Bucketer.java, core-api/src/main/java/com/optimizely/ab/bucketing/UserProfile.java, core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV1.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV3.java, core-api/src/test/java/com/optimizely/ab/bucketing/BucketerTest.java, gradle.properties
- This is simply un-reverting @mikeng13's commit https://github.com/optimizely/java-sdk/commit/b9c671a1504c331d6cfd47b96b7d3bf873b4baab
=> Rename UserExperimentRecord to UserProfile

.travis.yml
=> Allow for builds to be triggered on tag creation

core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/notification/NotificationBroadcaster.java, core-api/src/main/java/com/optimizely/ab/notification/NotificationListener.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTestV3.java, core-api/src/test/java/com/optimizely/ab/notification/NotificationBroadcasterTest.java
Reverts optimizely/java-sdk#52
=> Revert "Add onEventTracked listener"

core-api/build.gradle
=> Fix build version generation

CHANGELOG.md, core-api/src/main/java/com/optimizely/ab/config/Experiment.java, core-api/src/main/java/com/optimizely/ab/config/parser/GsonHelpers.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java, core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java, core-api/src/test/resources/config/valid-project-config-v2.json, gradle.properties
=> Default 'null' status to 'Not started'

CHANGELOG.md, gradle.properties
=> Prepare 1.6.0 release

core-api/src/main/java/com/optimizely/ab/event/internal/payload/Conversion.java
=> alphabetize fields in Conversion.java to make it more readable

core-api/src/main/java/com/optimizely/ab/bucketing/UserProfileService.java
=> user profile service

core-api/src/main/java/com/optimizely/ab/bucketing/UserProfileService.java
=> user profile service map structure

.travis.yml
=> stop building travis-ci against devel

.travis.yml
=> Configure travis-ci to ship alpha versions.

core-api/src/main/java/com/optimizely/ab/config/Feature.java
=> Add Features to SDK

core-api/src/test/resources/config/valid-project-config-v4.json
=> revise v4 datafile

core-api/src/main/java/com/optimizely/ab/Optimizely.java
=> Feature Accessor APIs

core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java, core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java, core-api/src/test/java/com/optimizely/ab/config/parser/GsonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JacksonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JsonConfigParserTest.java, core-api/src/test/java/com/optimizely/ab/config/parser/JsonSimpleConfigParserTest.java, core-api/src/test/resources/config/valid-project-config-v4.json
=> parse v4 additive json

core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java, core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java
=> parameterize optimizely unit tests with v4 datafile

core-api/src/main/java/com/optimizely/ab/config/LiveVariable.java, core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java
=> make status optional in the creation of live variables

core-api/src/main/java/com/optimizely/ab/config/FeatureFlag.java, core-api/src/main/java/com/optimizely/ab/config/parser/GsonHelpers.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java, core-api/src/test/resources/config/valid-project-config-v4.json
=> refactor layerId property of FeatureFlag class to rolloutId

.travis.yml, CHANGELOG.md
add change log information for beta 2. add regex rules for allowing numbers after semver tags
=> update changelog and travis.yml

gradle.properties
change version back to `2.0.0` since that is what master will be
Add `SNAPSHOT` back to end of version for e2e tests to pass
=> append SNAPSHOT to version

core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
Check for null value in the parameters for the feature APIs
=> Check for Null Parameters in the Feature APIs

core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
* Remove throws declarations on methods since we never actually throw. 
* Change docs to explain that we send it to the error handler instead
=> [WIP] Refactor experiment and events getters

core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/bucketing/DecisionService.java, core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java, core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigGsonDeserializer.java, core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigJacksonDeserializer.java, core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilder.java, core-api/src/main/java/com/optimizely/ab/event/internal/payload/Attribute.java, core-api/src/main/java/com/optimizely/ab/event/internal/payload/Decision.java, core-api/src/main/java/com/optimizely/ab/internal/ControlAttribute.java, core-api/src/main/java/com/optimizely/ab/internal/ReservedAttributeKey.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java, core-api/src/test/java/com/optimizely/ab/bucketing/DecisionServiceTest.java, core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTest.java, core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java, core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderTest.java, core-api/src/test/resources/config/valid-project-config-v4.json
* Added BotFiltering
* Added unit tests
=> Added BotFiltering

docs/readme.md
=> Added docs folder and in it we added instructions of how to generate documentation 

CHANGELOG.md
- Update the 3.0.0 rc.
* This includes a graceful shutdown method for AsyncEventHandler.
* This also includes json parsing for leaf nodes in condition trees.
=> (choir) update for latest RC

core-httpclient-impl/src/main/java/com/optimizely/ab/event/AsyncEventHandler.java
- Checked LogEvent request method type if it is get than generate get request and if it is post than generate post request.  
- failure asserting results[reach][total_count] == expectation.total_impressions
ERROR:root:expected 1 total visitors; actually found 0 total visitors
=> Fix(Impression event): Resolved method post issue 

CHANGELOG.md
- prepare for 2.1.4 patch release wrapping load file in try/catch.
There was a crash reported here effecting a very small group.
=> (chore): update changelog for patch release

core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/bucketing/DecisionService.java, core-api/src/main/java/com/optimizely/ab/bucketing/FeatureDecision.java, core-api/src/main/java/com/optimizely/ab/notification/DecisionNotification.java, core-api/src/main/java/com/optimizely/ab/notification/NotificationCenter.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java, core-api/src/test/java/com/optimizely/ab/bucketing/DecisionServiceTest.java
- Added source_info in decision info object of decision listener
- Changed DecisionSource experiment to feature-test
- Changed DecisionNotificatonType.Experiment to DecisionNotificatonType.AB_TEST and DecisionSource.Experiment to DecisionSource.Feature-test
- [OASIS-4508](https://optimizely.atlassian.net/projects/OASIS/issues/OASIS-4508)
=> Feat: Updated isFeatureEnabled notification listener implementation as per new design

gradle.properties
- Update version in gradle.properties
=> Update version in gradle.properties.

core-httpclient-impl/src/main/java/com/optimizely/ab/event/AsyncEventHandler.java, core-httpclient-impl/src/test/java/com/optimizely/ab/event/AsyncEventHandlerTest.java, java-quickstart/src/main/java/com/optimizely/Example.java
- Introducing builder pattern on AsyncEventHandler.
- Implemented AutoCloseable and defined close method to call our shutdownAndAwaitTermination method.
=> Introducing builder pattern on AsyncEventHandler

core-api/src/main/java/com/optimizely/ab/Optimizely.java, core-api/src/main/java/com/optimizely/ab/bucketing/DecisionService.java, core-api/src/main/java/com/optimizely/ab/config/PollingProjectConfigManager.java, core-api/src/main/java/com/optimizely/ab/event/internal/serializer/DefaultJsonSerializer.java, core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java, core-api/src/test/java/com/optimizely/ab/config/PollingProjectConfigManagerTest.java
- Fix logs leaking in JUnit test due to improper cleanup.
- Lower log level for common log output to reduce confusion.
- Fix erroneous log where features were reported as enabled and not enabled.
Unit tests
=> (refac): Improve logging levels for common logs.

core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java
Fixing incorrect error message in `HttpProjectConfigManager`
=> Fixing message in config manager

core-httpclient-impl/README.md
- Add docs for builder methods
- Add docs for update config notification
=> Update README.md for notifications and builder methods.

core-api/src/main/java/com/optimizely/ab/event/BatchEventProcessor.java, core-api/src/test/java/com/optimizely/ab/event/BatchEventProcessorTest.java
- Adds configurability options for the close timeout for `BatchEventProcessor`.
=> Make close timeout configurable.

CHANGELOG.md
- Update changelog for 3.4.0-beta release.
=> Update changelog for 3.4.0-beta release.

CHANGELOG.md
- Update changelog to release 3.2.1
=> Update changelog for 3.2.1.

CHANGELOG.md
- Update changelog for 3.3.2 release.
- Slight refactor on BatchEventProcessor.
=> (chore): prepare for 3.3.2 release

CHANGELOG.md
- Update CHANGELOG.md in preparation for patched releases
=> Update CHANGELOG for patching http client.

CHANGELOG.md
=> prepare for 3.4.0 release

CHANGELOG.md
=> chore: prepare for release 3.4.2

CHANGELOG.md
=> prepare for release 3.4.3

CHANGELOG.md
July 2nd, 2020
- Add support for JSON feature variables ([#372](https://github.com/optimizely/java-sdk/pull/372), [#371](https://github.com/optimizely/java-sdk/pull/371), [#375](https://github.com/optimizely/java-sdk/pull/375))
- Add support for authenticated datafile access ([#378](https://github.com/optimizely/java-sdk/pull/378))
- Adjust log level on audience evaluation logs ([#377](https://github.com/optimizely/java-sdk/pull/377))
=> (chore): prepare for release 3.5.0-beta

CHANGELOG.md
July 7th, 2020
- Add support for JSON feature variables ([#372](https://github.com/optimizely/java-sdk/pull/372), [#371](https://github.com/optimizely/java-sdk/pull/371), [#375](https://github.com/optimizely/java-sdk/pull/375))
- Add support for authenticated datafile access ([#378](https://github.com/optimizely/java-sdk/pull/378))
- Adjust log level on audience evaluation logs ([#377](https://github.com/optimizely/java-sdk/pull/377))
=> (chore): prepare for release 3.5.0

core-api/src/main/java/com/optimizely/ab/config/audience/match/SemanticVersion.java, core-api/src/test/java/com/optimizely/ab/config/audience/SemanticVersionTest.java
- Multiple fixed for sem-versioning
- Compare build version and pre-release fix
- Multiple `+` added.
All FSC tests must pass
Added unit tests
=> fix: Semantic version fix and multiple plus signs check added

core-httpclient-impl/gradle.properties, gradle.properties, java-quickstart/build.gradle
- Updated Apache Commons Code and Apache Log4j to update the dependencies to versions without known vulnerabilities.
All FSC and unit Tests must pass
=> Feat: Update Apache Commons Code and Apache Log4j.

build.gradle
- Just updated the plugin for bintray which fails on ship task.  This fixes that.
- used to publish 3.6.0
=> fix: update the gradle plugin for bintray.  The old plugin failed ship task

CHANGELOG.md, core-httpclient-impl/gradle.properties
=> chore: prepare for 3.7.0 release

java-quickstart/src/main/java/com/optimizely/Example.java
- Fix sample codes from legacy APIs to new decide APIs
=> chore: fix sample codes to use decide apis

CHANGELOG.md
- Prepare for release 3.8.0-beta2
=> chore: prepare for release 3.8.0-beta2

CHANGELOG.md
=> chore: prepare for 3.8.1

.travis.yml
- fix redundant publishing from travis
=> chore: fix redundant publishing from travis

README.md
- Update README about MavenCentral
=> chore: update README about MavenCentral

CHANGELOG.md
=> chore: Prepare for 3.9.0 Release

CHANGELOG.md
=> chore: prepare for release 3.10.0

README.md
Updating the URLs to the Java SDK documentation.
- Fixes #470
=> Updating doc urls

.github/workflows/integration_test.yml, .github/workflows/java.yml
- Git actions updated to run FSC on git actions.
- Need to change travisci-tools branch from `mnoman/gitActions` to `master`
=> feat: updated for fsc git action

CHANGELOG.md
Prepare for release 3.10.3
- [FSSDK-8953](https://jira.sso.episerver.net/browse/FSSDK-8953)
=> chore: prepare for release 3.10.3

CHANGELOG.md
Fix release date for 3.10.3
- [FSSDK-8953](https://jira.sso.episerver.net/browse/FSSDK-8953)
=> chore: fix release date

CHANGELOG.md
update CHANGELOG.md
- FSSDK-9436
=> [FSSDK-9436] chore: prepare for release 3.10.4

CHANGELOG.md
- Release 4.0.0-beta2
- FSSDK-9617
=> [FSSDK-9617] chore: release 4.0.0-beta2

CHANGELOG.md
prepare for release 4.1.0
- FSSDK-10041
=> [FSSDK-10041] chore: prepare fore release 4.1.0

CHANGELOG.md
prepare for v3.10.5
- "FSSDK-0000"
=> chore: prepare for v3.10.5

CHANGELOG.md
- prepare for release 4.1.1
- "FSSDK-0000"
=> chore: prepare for release 4.1.1

CHANGELOG.md, gradle.properties
=> [FSSDK-10839] prepare for release 4.2.0

.github/workflows/java.yml
Updating workflow versions
- EC3-1687 https://jira.sso.episerver.net/browse/EC3-1687
=> EC3-1687 workflow versions

CHANGELOG.md
- Release big integer conversion fix
- FSSDK-11193
=> [FSSDK-11193] chore: release 4.2.1

.github/workflows/build.yml, .github/workflows/java.yml, build.gradle
- Fix github release tag 
- FSSDK-11076
=> [FSSDK-11076] fix: release tag

CHANGELOG.md
- Prepare for release 4.2.2
- FSSDK-11465
=> [FSSDK-11465] chore: prepare for release 4.2.2
