optimizely/java-sdk

.travis.yml
README.md

@aliabbasrizvi @haleybash-optimizely @delikat

Update Travis badge to reflect public repo

---

.travis.yml

@haleybash-optimizely @delikat @aliabbasrizvi 
Build is breaking from authentication issues when auto-incrementing. Removing auto-increment temporarily to get the build passing again by running tests only.

Temporarily remove auto-incrementing

---

core-api/src/jmh/java/com/optimizely/ab/OptimizelyBenchmark.java
core-api/src/jmh/java/com/optimizely/ab/OptimizelyBuilderBenchmark.java

- Add checked exception handling to benchmark tests

Fix benchmark tests

---

CHANGELOG.md
CONTRIBUTING.md
README.md
core-api/src/jmh/java/com/optimizely/ab/OptimizelyBenchmark.java
core-api/src/jmh/java/com/optimizely/ab/OptimizelyBuilderBenchmark.java
core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/config/parser/ConfigParseException.java
core-api/src/main/java/com/optimizely/ab/config/parser/GsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JacksonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java
core-api/src/main/java/com/optimizely/ab/event/EventHandler.java
core-api/src/main/java/com/optimizely/ab/internal/ProjectValidationUtils.java
core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV1.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java
core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV1Test.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java
core-api/src/test/java/com/optimizely/ab/internal/ProjectValidationUtilsTestV1.java
core-api/src/test/java/com/optimizely/ab/internal/ProjectValidationUtilsTestV2.java
core-api/src/test/resources/config/valid-project-config-v1.json
core-api/src/test/resources/config/valid-project-config-v2.json
gradle.properties

Release version 1.0.0

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV2.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/Event.java
core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java

- Add `withClientEngine` and `withClientVersion` methods for Android to consume.

Add clientEngine and clientVersion configurability

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/bucketing/Bucketer.java
core-api/src/main/java/com/optimizely/ab/bucketing/UserProfile.java
core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV1.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java
core-api/src/test/java/com/optimizely/ab/bucketing/BucketerTest.java

Rename UserExperimentRecord to UserProfile.

---

core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigGsonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigJacksonDeserializer.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV2.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/Conversion.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/Impression.java
core-api/src/main/java/com/optimizely/ab/event/internal/serializer/JsonSimpleSerializer.java
core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTest.java
core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/SerializerTestUtils.java
core-api/src/test/resources/config/valid-project-config-v3.json
core-api/src/test/resources/serializer/conversion.json
core-api/src/test/resources/serializer/impression.json

Add IP anonymization to event payload.

---

CHANGELOG.md
core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV3.java

Change position of activateExperiment

---

core-api/build.gradle
core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/event/internal/BuildVersionInfo.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV1.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV2.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/Event.java
core-api/src/main/resources/.gitignore
core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java
gradle/license.gradle

Remove generated 'BuildConfig' class and add resource file to retrieve version info

---

core-api/src/main/java/com/optimizely/ab/bucketing/Bucketer.java
core-api/src/main/java/com/optimizely/ab/bucketing/UserProfile.java
core-api/src/test/java/com/optimizely/ab/bucketing/BucketerTest.java

Persist experiment and variation IDs instead of keys in UserProfile

---

CHANGELOG.md
gradle.properties

Prepare for 1.3.0 release

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/bucketing/Bucketer.java
core-api/src/main/java/com/optimizely/ab/config/Experiment.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV2.java
core-api/src/main/java/com/optimizely/ab/internal/ProjectValidationUtils.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java
core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java
core-api/src/test/resources/config/no-audience-project-config-v2.json

Add support for "Launched" experiment status

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilder.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV1.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV2.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/Conversion.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/Impression.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/LayerState.java
core-api/src/main/java/com/optimizely/ab/event/internal/serializer/JacksonSerializer.java
core-api/src/main/java/com/optimizely/ab/event/internal/serializer/JsonSimpleSerializer.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV1.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV3.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/GsonSerializerTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/JacksonSerializerTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/JsonSerializerTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/JsonSimpleSerializerTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/SerializerTestUtils.java
core-api/src/test/resources/serializer/conversion-session-id.json
core-api/src/test/resources/serializer/impression-session-id.json

Add sessionId and revision to event payload

---

CHANGELOG.md
core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/bucketing/Bucketer.java
core-api/src/main/java/com/optimizely/ab/config/Experiment.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilder.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV1.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV2.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/Conversion.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/Impression.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/LayerState.java
core-api/src/main/java/com/optimizely/ab/event/internal/serializer/JacksonSerializer.java
core-api/src/main/java/com/optimizely/ab/event/internal/serializer/JsonSimpleSerializer.java
core-api/src/main/java/com/optimizely/ab/internal/ProjectValidationUtils.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV1.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV3.java
core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/GsonSerializerTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/JacksonSerializerTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/JsonSerializerTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/JsonSimpleSerializerTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/serializer/SerializerTestUtils.java
core-api/src/test/resources/config/no-audience-project-config-v2.json
core-api/src/test/resources/serializer/conversion-session-id.json
core-api/src/test/resources/serializer/impression-session-id.json
gradle.properties

Release version 1.4.0

---

CHANGELOG.md
core-api/src/main/java/com/optimizely/ab/config/Experiment.java
core-api/src/main/java/com/optimizely/ab/config/parser/GsonHelpers.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java
core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java
core-api/src/test/resources/config/valid-project-config-v2.json
gradle.properties

Release version 1.4.1 (#71)

---

core-api/src/main/java/com/optimizely/ab/event/internal/payload/Event.java
core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java

Summary: Set client engine to android tv if SDK is used on AndroidTV

Add Android TV SDK client engine type to Event

---

CHANGELOG.md
gradle.properties

February 16, 2017
- Support Android TV SDK client engine

Prepare 1.5.0 release

---

core-api/src/test/java/com/optimizely/ab/OptimizelyTestV2.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTestV3.java

The datafiles and configs need to only be set up once per test.
Takes about 1 second of each test case run time.

Use `@BeforeClass` to do static set up.

---

.travis.yml
build.gradle
core-api/src/test/java/com/optimizely/ab/bucketing/BucketerTest.java

skip the exhaustive `generateBucketValueDistribution` when we're not testing on Travis Linux builds

speed up local build time by 97%

---

core-api/src/jmh/java/com/optimizely/ab/OptimizelyBenchmark.java
core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

remove revenue APIs

---

core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigGsonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigJacksonDeserializer.java

remove v1 datafile support

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java

deprecate live variable APIs

---

core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java
core-api/src/test/resources/config/valid-project-config-v4.json

create v4 test datafile

---

core-api/src/main/java/com/optimizely/ab/config/Layer.java
core-api/src/main/java/com/optimizely/ab/config/Rollout.java

add layers and rollouts

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/config/FeatureFlag.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/Feature.java
core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java
core-api/src/test/resources/config/valid-project-config-v4.json

add features to project config

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

remove live variable v3 APIs

---

core-api/src/main/java/com/optimizely/ab/config/FeatureFlag.java
core-api/src/main/java/com/optimizely/ab/config/LiveVariable.java
core-api/src/main/java/com/optimizely/ab/config/LiveVariableUsageInstance.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/Variation.java
core-api/src/main/java/com/optimizely/ab/config/parser/FeatureFlagGsonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/GsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/GsonHelpers.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigGsonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/ProjectConfigJacksonDeserializer.java
core-api/src/test/java/com/optimizely/ab/config/ProjectConfigTestUtils.java
core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java
core-api/src/test/java/com/optimizely/ab/config/parser/GsonConfigParserTest.java
core-api/src/test/java/com/optimizely/ab/internal/LogbackVerifier.java
core-api/src/test/resources/config/valid-project-config-v4.json

feature flag parsing

---

core-api/src/main/java/com/optimizely/ab/event/internal/EventBuilderV2.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/EventMetric.java
core-api/src/main/java/com/optimizely/ab/internal/EventTagUtils.java
core-api/src/main/java/com/optimizely/ab/internal/ReservedEventKey.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventBuilderV2Test.java

Add support for numeric metrics

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/bucketing/DecisionService.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/bucketing/DecisionServiceTest.java
core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java
core-api/src/test/resources/config/valid-project-config-v4.json

Create Feature Variable Accessor with type support
Create internal Decision Service method for features

internal feature variable accessor support

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

* link feature variable accessors to feature variable by value and type
* add unit tests for getFeatureVariable calling through to internals
* add unit tests to catch parsing error

feature variable accessor apis

---

.travis.yml

travis-ci switch builds to trusty by default it seems
we want `dist: precise` in configs

use precise distribution instead of trusty

---

core-api/src/main/java/com/optimizely/ab/bucketing/DecisionService.java

we do not need to check experiment status since the datafile will not have inactive experiments

ignore experiment status when bucketing rollout rule experiments

---

.travis.yml
CHANGELOG.md
core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java
core-api/src/test/resources/config/valid-project-config-v4.json

* if no live variable usage exists for the variable in the variation, return the default value
* add rollout with variation that does not change variable value in rollout rule. This means no live variable usage will be in datafile. need to fallback on default value
* add test to make sure we fall back on default value when variable usage not found in datafile

Merge master onto 2.0.x for beta2 release

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

* Added GetEnabledFeatures method and its unit tests

Added GetEnabledFeatures method and its unit tests

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/event/LogEvent.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventFactory.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/event/NoopEventHandlerTest.java

This PR moves the serialization from POJO to JSON into `LogEvent#getBody()`. This allows the serialization of the event to be offloaded to with the event handler when the HTTP request is built. This should be 100% backwards compatible with any existing `EventHandler` implementations. Initial benchmarks are much improved over the current master in tight loop simulations.
Stats after 100,000 calls to `activate(...)` in my simulation:
|Metric (us)|PR-199|2.0.0-beta2|2.0.0-SNAPSHOT|THIS PR|
|---|---|---|---|---|
|Min|21|2|3|1||
|Median|29|2|9|6||
|Mean|41|3.8|10.2|6.1||
|75th Pct|40|3|11|7||
|95th Pct|85|7|18|11||
|99th Pct|126|26|43|21||
|999th Pct|713|65|237|232||
|Max|11825|17732|34384|12845||
Note `2.0.0-beta2` was pre-batch endpoint, so isn't a valid comparison. Also performance runs can …

Move serialization to LogEvent.getBody().

---

core-api/build.gradle
core-httpclient-impl/gradle.properties
gradle.properties

Results from Source Clear were 1 vulnerability and several suggested library updates. The following changes were made largely with the suggestions Source Clear made. All the information below is also in our Source Clear account.
`Apache httpclient 4.5.2` had a security vulnerability, in which Source Clear suggests a package update. Looking through the Source Clear Vulnerability Database, `4.5.6` does not have any vulnerabilities and is the most recent package. (There were also 5.0 beta versions that were breaking our code.)
There were several libraries that were outdated, in which some libraries were dependent on other libraries. The only library upgrade suggestion that I did not follow was `SLF4J 1.8.0-beta2`, and I upgraded it to `1.7.25` instead. `1.8.0-beta2` broke the code, so I …

Source Clear Improvements

---

core-api/src/main/java/com/optimizely/ab/event/internal/EventFactory.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventFactoryTest.java

This will ignore attributes with null values on creation of impression or conversion event.

fix(nullfilter): filters out attributes with null values

---

.travis.yml

This allows us to run Travis CI unit tests on release branches for minor versions: 2.1.x, 2.0.x, etc

chore: Enable Travis builds on release branches.

---

.travis.yml
CHANGELOG.md
core-api/src/main/java/com/optimizely/ab/event/internal/EventFactory.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventFactoryTest.java

This cherry-picks #214 and #215 into the 2.1.x release branch.
The Compat Suite runs on the latest version of the testapp, which is built from the master branch and already has changes to support the 3.0 release. Therefore, this particular release branch compile with that testapp version and we can't run the compat suite tests on it. 
Instead, I've checked out a different branch of the testapp and ran the compat suite tests locally against this PR.

chore: Prepare release branch for new release

---

core-api/src/main/java/com/optimizely/ab/config/audience/match/ExactNumberMatch.java
core-api/src/main/java/com/optimizely/ab/config/audience/match/MatchType.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java
core-api/src/test/java/com/optimizely/ab/config/audience/AudienceConditionEvaluationTest.java
core-api/src/test/resources/config/valid-project-config-v4.json

fix(core):Add a new match type for numbers exact match
The object.equals method will use Double.equals and fail if the Number is an Integer.  So, added an explicit ExactNumberMatch to compare actual values.
This fix was relatively small and does not have a large impact.  But, added tests to make sure that "exact" match works for both double and integer.

fix: created a new matcher for numbers

---

core-api/src/main/java/com/optimizely/ab/config/parser/AudienceGsonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/GsonHelpers.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java
core-api/src/main/java/com/optimizely/ab/internal/ConditionUtils.java

- Refactor to allow for any single leaf or array of leafs to be parsed in typedAudienceConditions and Experiment.audienceConditions
For consistency across SDKs
No additional tests were written.
- 3755

feat: refactor to allow for parsing of any single leaf or array of leafs

---

core-api/src/main/java/com/optimizely/ab/config/parser/AudienceJacksonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/ConditionJacksonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/GsonHelpers.java
core-api/src/main/java/com/optimizely/ab/config/parser/TypedAudienceJacksonDeserializer.java
core-api/src/main/java/com/optimizely/ab/internal/ConditionUtils.java
core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java
core-api/src/test/java/com/optimizely/ab/config/parser/GsonConfigParserTest.java
core-api/src/test/java/com/optimizely/ab/config/parser/JacksonConfigParserTest.java
core-api/src/test/java/com/optimizely/ab/config/parser/JsonConfigParserTest.java
core-api/src/test/java/com/optimizely/ab/config/parser/JsonSimpleConfigParserTest.java
core-api/src/test/resources/config/valid-project-config-v4.json

- After adding some compatibility tests, we discovered there were some errors in single leaf processing.  Fixed those and added tests.
Added unit tests in all json parsers for single leaf parsing.  
Added a single leaf node in the datafile and have all parsers parse it the same.
- Java SDK was failing compatibility tests.

(fix): added unit tests for leaf node parsing

---

CHANGELOG.md
core-api/src/main/java/com/optimizely/ab/event/internal/BuildVersionInfo.java

- Fix for possible problem loading file from static variable initializer.

(chore):Fix2.1.5

---

core-api/src/test/java/com/optimizely/ab/event/internal/EventFactoryTest.java

Follow up from easy event tracking change to update unit tests.

Updating unit tests in EventFactoryTest

---

build.gradle
core-api/build.gradle
core-httpclient-impl/build.gradle

The `com.optimizely.ab.categories.ExhaustiveTest` JUnit test category
marker is defined in the core-api subproject. It is also only used in the
core-api subproject.
Isolate the configuration to use this class to the core-api subproject
by moving out of the root `build.gradle`. This way, we can remove
core-api's testSources as a dependency of core-httpclient-impl's
testSources, as well as any additional subprojects that are added to
this repository.
Bringing this up because I noticed the following:
*   If you create a subproject (experimenting in a local branch), you won't 
be able to run tests because a `ClassNotFound` exception gets thrown
because root `build.gradle` prescribes this JUnit config to all `subprojects`
*  I noticed that core-httpclient-impl compiles every time you modify …

Better way to configure ExhaustiveTest JUnit category

---

README.md
build.gradle

- Finally drop source compatibility for Java 7 which has not been supported since 2015.

(feat): upgrade to source compatibility to java 8.  finally dropping 7

---

CHANGELOG.md

- Update the change log for 3.0 release

(chore) prepare for 3.0

---

CONTRIBUTING.md
build.gradle
core-api/src/main/java/com/optimizely/ab/config/audience/EmptyCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/NullCondition.java
core-api/src/main/java/com/optimizely/ab/config/parser/TypedAudienceJacksonDeserializer.java
core-api/src/test/java/com/optimizely/ab/internal/LogbackVerifier.java
resources/HEADER

Adds the [`com.github.hierynomus.license`][plugin] Gradle plugin that will verify
all source files have license header when the `check` task runs (i.e. tests).
The plugin will handle adding headers to files that are missing it (i.e.
check failures) by running the `licenseFormatMain` or `licenseFormatTest` task,
depending on which source set the file belongs to.
See [plugin][] documentation for more information.
[plugin]: https://github.com/hierynomus/license-gradle-plugin

Automate license headers

---

core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

- Simplify parameterization of OptimizelyTest
- Build ProjectConfig directly from the datafile JSON to ensure isolation between tests.
- Update individual tests that were reliant on previous test state.
These changes fix the non-determinism between test cases within OptimizelyTest. This was caused by passing singleton instances of ProjectConfig to the parameterized test runner, which were being mutated via calls to `setForcedVariation` in certain test cases.
This is a pure refactor to improve test repeatability. No new tests were added, but existing tests were updated to reflect their expected state.

Fix test isolation in OptimizelyTest class.

---

.travis.yml
core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

- Feature variable APIs now return default variable value when featureEnabled property is false.
Added unit tests.

feat(api): Feature variable APIs now return default variable value when featureEnabled property is false.

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/bucketing/DecisionService.java
core-api/src/main/java/com/optimizely/ab/bucketing/FeatureDecision.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfigUtils.java
core-api/src/main/java/com/optimizely/ab/notification/DecisionNotification.java
core-api/src/main/java/com/optimizely/ab/notification/NotificationCenter.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/bucketing/DecisionServiceTest.java

- Added source_info in decision info object of decision listener
- Changed DecisionSource experiment to feature-test
- Added one more DecisionNotificationType of feature-test
- Changed DecisionNotificatonType.Experiment to DecisionNotificatonType.AB_TEST and DecisionSource.Experiment to DecisionSource.Feature-test
- [OASIS-4508](https://optimizely.atlassian.net/projects/OASIS/issues/OASIS-4508)

Feat: Updated Activate/Variation notification listener implementation as per new design

---

core-api/src/main/java/com/optimizely/ab/notification/DecisionNotification.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

- sending decision source rollout and feature-test keys by adding toString().   
- This change is due to currently source value ROLLOUT and FEATURE_TEST was getting sent in notification.
Updated unit Tests

Fix: Added toString() on decisionSource so that rollout keys of enums get picked

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/notification/DecisionNotification.java
core-api/src/main/java/com/optimizely/ab/notification/FeatureTestSourceInfo.java
core-api/src/main/java/com/optimizely/ab/notification/RolloutSourceInfo.java
core-api/src/main/java/com/optimizely/ab/notification/SourceInfo.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

- [OASIS-4533](https://optimizely.atlassian.net/browse/OASIS-4533)

Refac: Refactored Decision Listener SourceInfo as per discussion

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/notification/DecisionNotification.java
core-api/src/test/java/com/optimizely/ab/notification/DecisionNotificationTest.java
core-api/src/test/java/com/optimizely/ab/notification/FeatureTestSourceInfoTest.java
core-api/src/test/java/com/optimizely/ab/notification/RolloutSourceInfoTest.java

Thanks to @mikecdavis for pointing out missing coverage in our unit tests.
Added tests for classes:
- DecisionNotification
- FeatureTestSourceInfo
- RolloutSourceInfo
Also renamed `newFeatureVariableBuilder` --> `newFeatureVariableDecisionNotificationBuilder`. 
Was unsure if I should add more tests per builder in `DecisionNotification.java`. Feedback welcome on that.

Adding missing unit tests related to notification listener 

---

core-api/src/main/java/com/optimizely/ab/notification/NotificationCenter.java
core-api/src/main/java/com/optimizely/ab/notification/NotificationManager.java
core-api/src/test/java/com/optimizely/ab/notification/NotificationManagerTest.java

- Catch all exceptions thrown from NotificationHandlers.
This fixes a regression in #288 refactor when a `NotificationHandler` throws an error.

Catch errors thrown while sending notifications.

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

Making Optimizely `Autocloseable` and calling close on `EventHandler` and `ProjectConfigManager` if they are `Closeable` themselves.

Making Optimizely Autocloseable

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/notification/NotificationCenter.java
core-api/src/test/java/com/optimizely/ab/notification/NotificationCenterTest.java
core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyFactory.java
core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java
core-httpclient-impl/src/test/java/com/optimizely/ab/config/HttpProjectConfigManagerTest.java

- Prevent NPE in HttpProjectConfigManager.Builder.
- Move `addNotificationHandler` into `NotificationCenter`
After further integration and dog-fooding these changes were made to improve overall usability.
Unit and compatibility test suite

Improve usability of the HttpProjectConfigManager.

---

core-httpclient-impl/README.md
core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java
core-httpclient-impl/src/test/java/com/optimizely/ab/config/HttpProjectConfigManagerTest.java

- Add package level README.md for core-httpclient-impl
- Fix bug where invalid input was not defaulted as the log indicates.

Add package level README.md for core-httpclient-impl

---

core-httpclient-impl/README.md

- Incorporate copy edits suggested [here|https://github.com/optimizely/java-sdk/pull/305]
- Differences with the copy edits are line spacing in the code samples and also including line breaks to make it easier to read without formatting applied.
- Copy edits also implied the existence of `optimizely.properties`, but users must supply one.

Incorporate copy edits.

---

core-httpclient-impl/src/main/java/com/optimizely/ab/event/AsyncEventHandler.java

Restoring and marking them as deprecated

Restoring constructors for AsyncEventHandler

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

This change fixes:
- `Optimizely.close()` which currently checks that `eventHandler` and `projectConfigManager` are instances of `Closeable`. Changing that to check if they are instances of `AutoCloseable`.
- `ProjectConfig` is refetched every time in `getVariation`. Using the passing in config itself.
- `ProjectConfig` is fetched multiple times when `getEnabledFeatures` is called. Updating `isFeatureEnabled`.
- Unit tests.

Fixing how project config is updated. Also, fixing issue in Optimizely.close()

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/event/LogEvent.java
core-api/src/test/java/com/optimizely/ab/EventHandlerRule.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/bucketing/DecisionServiceTest.java
core-api/src/test/java/com/optimizely/ab/config/PollingProjectConfigManagerTest.java
core-api/src/test/java/com/optimizely/ab/error/RaiseExceptionErrorHandlerTest.java
core-api/src/test/java/com/optimizely/ab/event/LogEventTest.java
core-api/src/test/java/com/optimizely/ab/event/NoopEventHandlerTest.java
core-api/src/test/java/com/optimizely/ab/internal/LogbackVerifier.java
core-api/src/test/java/com/optimizely/ab/notification/NotificationCenterTest.java

- Removes mockito from LogbackVerifier
- Adds EventHandlerRule for validating dispatched events.
- Removes dependency on mocked classes for the majority of tests.
- Some stylized refactoring to condense statements.
The overuse of Mockito has made the tests fairly brittle and also required a large amount of setup for each specific test. Moving to a more black box approach and verify the side-effects of the scenarios makes for much cleaner and more concise tests.
This is also a prerequisite for a larger change to the event processing in which we'll be batching requests to the log endpoint. If this refactor was not done, then we'd have to change all of the mock setups related to dispatching at that time which would erode confidence that we're maintaining parity when introducing that change.

Refactor OptimizelyTest to have less reliance on Mockito.

---

core-api/src/main/java/com/optimizely/ab/config/PollingProjectConfigManager.java
core-api/src/test/java/com/optimizely/ab/config/PollingProjectConfigManagerTest.java

- Trigger the UpdateConfigNotification after resolving the countdownlatch.
Since notifications are triggered synchronously in the calling thread, there was potential to unnecessarily block until the timeout if the notification listener was also calling `.getConfig()`
Unit test was added to confirm the issue, then validate the solution.

Fix blocking behavior when sending update notification.

---

CHANGELOG.md

- Update CHANGELOG.md for 3.2.0 release.

Update CHANGELOG.md for 3.2.0 release.

---

.travis.yml
core-api/src/main/java/com/optimizely/ab/config/parser/DefaultConfigParser.java
core-api/src/test/java/com/optimizely/ab/config/parser/DefaultConfigParserTest.java

Modified travis file to test all unit tests with default config parsers and default config parser is now set using ENV. 
All Parsers are defined in matrix to run all unit tests with each parser.
Unit tests should be pased
- "THING-1234" or "Fixes #123"

test(parser): Default parser

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/event/BatchEventProcessor.java
core-api/src/main/java/com/optimizely/ab/event/EventHandler.java
core-api/src/main/java/com/optimizely/ab/event/EventProcessor.java
core-api/src/main/java/com/optimizely/ab/event/ForwardingEventProcessor.java
core-api/src/main/java/com/optimizely/ab/event/internal/ConversionEvent.java
core-api/src/main/java/com/optimizely/ab/event/internal/ImpressionEvent.java
core-api/src/main/java/com/optimizely/ab/event/internal/UserContext.java
core-api/src/main/java/com/optimizely/ab/notification/NotificationCenter.java
core-api/src/main/java/com/optimizely/ab/notification/NotificationManager.java
core-api/src/test/java/com/optimizely/ab/EventHandlerRule.java
core-api/src/test/java/com/optimizely/ab/OptimizelyRule.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/event/BatchEventProcessorTest.java
core-api/src/test/java/com/optimizely/ab/event/ForwardingEventProcessorTest.java
core-api/src/test/java/com/optimizely/ab/notification/NotificationManagerTest.java
core-httpclient-impl/src/main/java/com/optimizely/ab/event/AsyncEventHandler.java

- Introduces an EventProcessor interface.
- Introduces a BatchEventProcessor (maybe should name it BatchingEventProcessor)
- Introduces an OptimizelyRule to handle lifecycle management during unit testing.
Buffering events within a queue before dispatching is an optimization that should prevent SDK implementations from exhausting resources while increasing throughput. This implementation relies on a `BlockingQueue` to buffer events received from one-to-many producers. A single consumer thread continuously polls from this queue to build a batch before emitting the batched `LogEvent`.
Note that the `Optimizely` class only knows about the `EventProcessor` and `EventHandler` so that it can gracefully close those implementations, so not strictly necessary. The Optimizely class builds …

Implement Event Batching Take2

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/event/BatchEventProcessor.java
core-api/src/main/java/com/optimizely/ab/event/ForwardingEventProcessor.java
core-api/src/main/java/com/optimizely/ab/notification/ActivateNotification.java
core-api/src/main/java/com/optimizely/ab/notification/NotificationCenter.java
core-api/src/main/java/com/optimizely/ab/notification/TrackNotification.java
core-api/src/test/java/com/optimizely/ab/OptimizelyRule.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/event/BatchEventProcessorTest.java
core-api/src/test/java/com/optimizely/ab/event/ForwardingEventProcessorTest.java
core-api/src/test/java/com/optimizely/ab/notification/NotificationCenterTest.java

- Add explicit notification for LogEvent.
- Deprecate LogEvent in track and activate notifications.
With the introduction of the BatchEventProcessor we no longer have a one-to-one mapping of Optimizely API calls to LogEvents dispatched. This PR adds a notification every time a LogEvent is built and submitted to the EventHandler. This can be subscribed to by adding a `NotificationHandler<LogEvent>` directly to the `NotificationCenter` or via the `Optimizely#addLogEventNotificationHandler(NotificationHandler)` convenience method.
We're also deprecating the LogEvent as a member of the `TrackNotification` and `ActivateNotification` models.

 Add LogEvent notification.

---

core-api/src/main/java/com/optimizely/ab/event/BatchEventProcessor.java
core-api/src/test/java/com/optimizely/ab/event/BatchEventProcessorTest.java

- Add flush method to BatchEventProcessor.
- Allow BatchEventProcessor to be restarted.
- Add option to build BatchEventProcessor without starting the processing thread.

Add more control over BatchEventProcessor.

---

core-api/src/main/java/com/optimizely/ab/config/parser/DefaultConfigParser.java

- Replace method reference with lambda in `DefaultConfigParser`
A recent change broke the selective class instantiating capability.
Run the java-quickstart example.
- OASIS-5052

Replace method reference to lambda in DefaultConfigParser.

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/event/BatchEventProcessor.java
core-api/src/main/java/com/optimizely/ab/internal/SafetyUtils.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/event/BatchEventProcessorTest.java
core-api/src/test/java/com/optimizely/ab/internal/SafetyUtilsTest.java
core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyFactory.java
core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyFactoryTest.java

- Default to using `BatchEventProcessor` when using `OptimizelyFactory`.
- Lower the default batch size to reduce impact of an SDK upgrade.

Incorporate batch processing into OptimizelyFactory.

---

core-api/README.md
core-api/src/main/java/com/optimizely/ab/event/BatchEventProcessor.java
core-httpclient-impl/README.md

- Add README to core-api package
- Update docs in core-httpclient-impl package to include `BatchEventProcessor`
Historically documentation has been deferred to the developers site, but those documents are geared towards implementation rather than development. This PR aims to add more documentation coverage for developers of the Java SDK.

Add more documentation.

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java

- Make `Optimizely.Builder#withDatafile` public.
- Add docs articulating the migration path away from the current factory method.
This should get patched into version `3.2.1` and will allow the Android SDK to cleanly use non-deprecated methods.

Add clear deprecation path from factory builder method.

---

core-api/src/main/java/com/optimizely/ab/event/BatchEventProcessor.java
core-api/src/test/java/com/optimizely/ab/EventHandlerRule.java
core-api/src/test/java/com/optimizely/ab/event/BatchEventProcessorTest.java

- Reverts to default config values when invalid for BatchEventProcessor.
- Adds expectedCall count to EventHandlerRule to simplify tests.

Defend against invalid BatchEventProcessor configuration overrides.

---

CHANGELOG.md

Updates the changelog for 3.3.0 release.
Note: the 3.3.0 release is based on the same commit as 3.4.0-beta but will cherry pick in this commit along with https://github.com/optimizely/java-sdk/commit/1395729dec031bc375e1a16896f31583027c076f which was patched into 3.2.1, but never included in 3.4.0-beta.

Update changelog for 3.3.0 release.

---

core-api/src/main/java/com/optimizely/ab/config/parser/DefaultConfigParser.java

- This has been tested on all supported versions and it works now.  We will also need to release 3.3.1 to patch this for Android.
Tested on Android.  It will also work on travis after this fix.  Travis builds won't pass with 3.3.0
Android versions < API 24 can't use java.util.Supplier.  This replaces Supplier with a local ParserSupplier which allows it to work on all versions of Android.

(fix): use a ParserSupplier instead of java.util.Supplier to enable work on older versions of Android.

---

CHANGELOG.md

- We have added support for older versions of Android (under API 24) by not using java.util.Supplier which is not supported in java 8 on these older versions. Change log update for release of 3.3.1
Change log change.

(chore): update for new release for android support

---

CHANGELOG.md
core-api/src/main/java/com/optimizely/ab/config/parser/DefaultConfigParser.java

(chore): chrerry pick changes to 3.3.x.

---

core-api/src/main/java/com/optimizely/ab/event/BatchEventProcessor.java
core-api/src/test/java/com/optimizely/ab/event/BatchEventProcessorTest.java

- pass in current time - flush interval to polling mechanism.
- use take instead of poll if we have been cycling more than twice.
- reset deadline once we hit it so it doesn't repeat until next flush interval.
FSC test?

(chore): refactor batch event processor to use blocking queue poll and take so as not to spin too much.

---

CHANGELOG.md
core-api/src/main/java/com/optimizely/ab/Optimizely.java

- Catching some PRs we missed.

(chore): release off of master

---

core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyHttpClient.java
core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyHttpClientTest.java
java-quickstart/build.gradle

- Use system properties with custom http client.
This enables http client settings (e.g. `http.proxyHost`, etc) to be set via system properties.
- Unit test ensuring system properties are getting pulled in.
- Manually tested by running a local proxy and the provided example via `./gradlew -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8888 runExample`
- OASIS-5725

Add support for native http proxying.

---

core-api/src/main/java/com/optimizely/ab/config/audience/AudienceIdCondition.java
core-api/src/main/java/com/optimizely/ab/internal/ConditionUtils.java

The Logger name for `AudienceIdCondition.java` is currently just the static string "AudienceIdCondition". This means that it's not possible to change the log level of this class using the `com.optimizely` group.
This should be changed to use the class `AudienceIdCondition.class` itself.

Properly set logger name for AudienceIdCondition and ConditionUtils

---

core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigService.java

- Removed Java 8 supported functions to support android api 21 and 22

Refact: Removed usage of stream from optimizelyConfig service to support android api 21 and 22

---

CHANGELOG.md

chore: prepare for release 3.4.1

---

.travis.yml
CHANGELOG.md
core-api/README.md

- The "what"; a concise description of each logical change
- Another change
- "THING-1234" or "Fixes #123"

ci(travis): add mdspell

---

core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java

Change logging "Fetching data file from..." to debug level from info.
Info level logging on this is causing us two problems:
1) It's spamming our logs (which company wide are info) with this log line
2) We don't want the datafile name, which happens to correspond to the api key in our logs either
Debug solves both of these and we can optionally turn it on if we are seeing issues with datafile fetching.
N/A, only logging level
N/A

[HttpProjectConfigManager] Change "Fetching datafile from" log to debug level

---

core-api/src/main/java/com/optimizely/ab/config/DatafileProjectConfig.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java

- This changes the log severity level to be `WARN` when experiment and event names are passed that are not in the datafile. Currently it is an `ERROR`, however that seems to be too severe since the situation is completely recoverable. (see #353)
- Pass in experiment name and event name that does not exist, make sure error is logged at `WARN` severity level
- fixes #353

(fix) change log level to warn when experiment not in datafile

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/config/FeatureVariable.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java
core-api/src/main/java/com/optimizely/ab/notification/DecisionNotification.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigService.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java
core-api/src/test/java/com/optimizely/ab/notification/DecisionNotificationTest.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigServiceTest.java
core-api/src/test/resources/config/valid-project-config-v4.json

- FeatureVariable Type was Enum with fixed types, which does not support future types (JSON, etc). 
- Change the type to String for forward compatibility
- Add a variable with undefined type name and make sure SDK does not crash

fix: change FeatureVariable type to string for forward compatibility

---

core-api/src/main/java/com/optimizely/ab/config/audience/AudienceIdCondition.java
core-api/src/main/java/com/optimizely/ab/internal/ExperimentUtils.java
core-api/src/test/java/com/optimizely/ab/internal/ExperimentUtilsTest.java

- Updating audience evaluation log level to be debug. The only info level log will be the one corresponding to the result of overall evaluation of an audience.

fix(log-level) Adjusting log level on audience evaluation logs

---

core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyFactory.java
core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java
core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyFactoryTest.java
core-httpclient-impl/src/test/java/com/optimizely/ab/config/HttpProjectConfigManagerTest.java

- add support for authenticated datafile access
- auth-token can be set by calling either
(1) Optimizely optimizely = OptimizelyFactory.newDefaultInstance(String sdkKey, 
String authDatafileToken, 
String fallback); or
(2) HttpProjectConfigManager.Builder builder = HttpProjectConfigManager.builder()
.withSdkKey(sdkKey)
.withAuthDatafileToken(authDatafileToken);
Optimizely optimizely = OptimizelyFactory.newDefaultInstance(builder.build());
- test the target url and authenticated header are set appropriately both when auth-token is specified (authenticated datafile) or not (regular datafaile)

feat: add support for authenticated datafile access

---

.travis.yml
core-httpclient-impl/README.md
core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyFactory.java
core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyFactoryTest.java

-  Adds “OptimizelyFactory#setDatafileAccessToken(string) method
- Removed spell checker.
- Added unit tests and other unit tests should pass and all FSC scenarios should pass

Feat: Added SetDatafileAccessToken method in OptimizelyFactory

---

build.gradle
core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyHttpClientTest.java
gradle/wrapper/gradle-wrapper.properties

- replaced findbugs with spotbugs as its no longer supported.
- changed setting Directory variables of Jacoco to use setFrom as syntax has been changed in latest update

Updated gradle version to gradle 6

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/bucketing/DecisionService.java
core-api/src/main/java/com/optimizely/ab/config/audience/AudienceIdCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/UserAttribute.java
core-api/src/main/java/com/optimizely/ab/config/audience/match/UnexpectedValueTypeException.java
core-api/src/main/java/com/optimizely/ab/internal/ExperimentUtils.java
core-api/src/main/java/com/optimizely/ab/internal/LoggingConstants.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/bucketing/DecisionServiceTest.java
core-api/src/test/java/com/optimizely/ab/config/audience/AudienceConditionEvaluationTest.java
core-api/src/test/java/com/optimizely/ab/internal/ExperimentUtilsTest.java

- Added and updated missing audience evaluation logs.
added unit tests must pass and all FSC scenarios should pass

refact(audience-logs): Added and refactored audience and feature variable evaluation logs

---

.travis.yml

Summary
-------
Stages run sequentially on Travis. If a stage fails, all the following stages are not executed. We execute source clear only on cron, and if due to any reason unit or integration tests fail, the source clear is not executed. Hence, moving source clear stage before tests. 
Test plan
---------
All unit tests must be passed. 
FSC must be passed.

ci: Run source clear before linting and tests.

---

core-api/src/main/java/com/optimizely/ab/config/DatafileProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfig.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigService.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/config/DatafileProjectConfigBuilderTest.java

Summary
-------
- Add datafile accessor methods/functionalities
Testing
-------
- All unit tests and FSC must pass
https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/181371500

feat: Add datafile accessor

---

core-api/src/main/java/com/optimizely/ab/config/audience/match/SemanticVersion.java
core-api/src/test/java/com/optimizely/ab/config/audience/SemanticVersionTest.java

- contains unit tests of invalid scenarios in which semantic version should return null and throw exception.
- added dot count function to to verify if the count of dot is smaller than prefixVersion count.
Unit tests added and did Manual FSC testing

Feat: Added Semantic versioning invalid scenarios unit Tests.

---

.travis.yml
java-quickstart/build.gradle

- Replaced slf4j-log4j12 lib with slf4j-simple due to vulnerability issue in log4j 1.2 version
- Also this PR will resolve the logging issue in quick-start application
FSC and all unit tests should pass.

Fix: logging issue in quick-start application

---

CHANGELOG.md

- update for release off of master of 3.6 includes semver and datafile accessors.

chore: 3.6 release

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/config/DatafileProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/parser/DatafileGsonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/DatafileJacksonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventFactory.java
core-api/src/main/java/com/optimizely/ab/event/internal/ImpressionEvent.java
core-api/src/main/java/com/optimizely/ab/event/internal/UserEventFactory.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/Decision.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/DecisionMetadata.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventFactoryTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/UserEventFactoryTest.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigServiceTest.java
core-api/src/test/resources/config/valid-project-config-v4.json

* Add experiment/feature flag key, variation key and type to impression events.
* Send events for **ALL** decision types.
* Add `Metadata` field to EventBatch.Decisions to capture flag type, key and variation key.
* All FSC and unit tests should pass

feat(flag-decisions): Add support for sending flag decisions along with decision metadata. 

---

CONTRIBUTING.md

- The "what"; a concise description of each logical change
- Another change
- "THING-1234" or "Fixes #123"

docs: Updated CONTRIBUTING.md to remove duplicate text

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/event/internal/UserEventFactory.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/DecisionMetadata.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventFactoryTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/UserEventFactoryTest.java

- While sending impression events, metadata should have enabled field as well.
- updated unit tests
- FSC should pass

feat: added enabled field in metadata.

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java

- IsFeatureEnabled was sending impression before finalizing all checks of feature enabled. Just made it after finalization.
- can't add unit tests. 
- only FSC should be passed.

fix: decision metadata enabled fix.

---

core-api/src/main/java/com/optimizely/ab/OptimizelyUserContext.java
core-api/src/main/java/com/optimizely/ab/optimizelydecision/OptimizelyDecision.java

Clone the current user-context and pass it to optimizely.decide()
- user context can be changed while processing the decide request.
- with this fix, decide can return the copy of the original user-context as a part of the decision
- Validate user-context are copied and passed as expected

feat(decide): clone user-context before calling optimizely decide

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyUserContextTest.java

- SendImpressionEvent will return false when event is not sent and return true when sent successfully
- In case of userEvent is null it will return false

Fix: SendImpressionEvent will return false when event is not sent

---

core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java
core-httpclient-impl/src/test/java/com/optimizely/ab/config/HttpProjectConfigManagerTest.java

- close the closable response from apache httpclient.
- 
- "Possible fix for #416"

fix: close the closable response.

---

CHANGELOG.md

chore: prepare for release 3.8.0

---

core-api/src/main/java/com/optimizely/ab/bucketing/DecisionService.java

- GetVariationForFeatureInRollout to return null decisionResponse when rolloutRulesLength is zero

Fix: GetVariationForFeatureInRollout to return null decisionResponse when rolloutRulesLength is zero

---

build.gradle
java-quickstart/build.gradle

- Upload maven artifacts to maven-central (pom, signing)
- Refer to this guide doc: https://central.sonatype.org/pages/ossrh-guide.html
- OASIS-7439

chore: migrate upload repository to maven-central from jcenter

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/OptimizelyUserContext.java
core-api/src/main/java/com/optimizely/ab/config/DatafileProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfigUtils.java
core-api/src/main/java/com/optimizely/ab/config/audience/AudienceIdCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/match/MatchRegistry.java
core-api/src/main/java/com/optimizely/ab/config/audience/match/SemanticVersion.java
core-api/src/main/java/com/optimizely/ab/config/parser/ConfigParser.java
core-api/src/main/java/com/optimizely/ab/event/BatchEventProcessor.java
core-api/src/main/java/com/optimizely/ab/internal/ConditionUtils.java
core-api/src/main/java/com/optimizely/ab/internal/EventTagUtils.java
core-api/src/main/java/com/optimizely/ab/internal/PropertyUtils.java
core-api/src/main/java/com/optimizely/ab/internal/SafetyUtils.java
core-api/src/main/java/com/optimizely/ab/notification/ActivateNotification.java
core-api/src/main/java/com/optimizely/ab/notification/NotificationCenter.java
core-api/src/main/java/com/optimizely/ab/notification/TrackNotification.java
core-api/src/main/java/com/optimizely/ab/optimizelyjson/OptimizelyJSON.java
core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyFactory.java
core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java
core-httpclient-impl/src/main/java/com/optimizely/ab/event/AsyncEventHandler.java

- Clean up all javadoc warnings

fix: clean up all javadoc warnings

---

core-api/src/main/java/com/optimizely/ab/event/internal/payload/Decision.java

- Added JsonInclude as always when serializing on campaign and experiment id.
- This is to make sure that decision object contains campaign and experiment id even when null.
- This change is just to pass the tests on FSC as while serialization of dispatched event rollout campaign id and experiment id was missing because they were null.

Fix:  Added JsonInclude as always when serializing on campaign and experiment id. 

---

core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyFactory.java
core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyHttpClient.java
core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java
core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyFactoryTest.java
core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyHttpClientTest.java
core-httpclient-impl/src/test/java/com/optimizely/ab/config/HttpProjectConfigManagerTest.java

- With periodic polling, datafile fetches may fail with timeout intermittently. 
- Add configurable "evictIdleConnections" to HttpProjectConfigManager to force close persistent connection after idle time (evict after 1min idle time by default).
- OASIS-7421

fix: add configurable evictIdleConnections

---

CHANGELOG.md

chore: prepare for release 3.8.2

---

core-api/src/main/java/com/optimizely/ab/config/DatafileProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/parser/DatafileGsonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/DatafileJacksonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfig.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigService.java
core-api/src/test/java/com/optimizely/ab/config/PollingProjectConfigManagerTest.java
core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigServiceTest.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigTest.java
core-api/src/test/resources/config/valid-project-config-v4.json
core-httpclient-impl/src/test/resources/valid-project-config-v4.json

- Sdk key and environment keys are going to be parse in sdk and will be sent back in optimizelyConfig
All unit tests and FSC tests should pass

Feat: added SDKkey and environment in datafile

---

core-api/src/main/java/com/optimizely/ab/config/Experiment.java
core-api/src/main/java/com/optimizely/ab/config/Variation.java
core-api/src/main/java/com/optimizely/ab/config/audience/AndCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/AudienceIdCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/Condition.java
core-api/src/main/java/com/optimizely/ab/config/audience/EmptyCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/NotCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/NullCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/OrCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/UserAttribute.java
core-api/src/main/java/com/optimizely/ab/config/parser/ConditionJacksonDeserializer.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/internal/ConditionUtils.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyAttribute.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyAudience.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfig.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigService.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyEvent.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyExperiment.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyFeature.java
core-api/src/test/java/com/optimizely/ab/config/ExperimentTest.java
core-api/src/test/java/com/optimizely/ab/config/audience/AudienceConditionEvaluationTest.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyAttributeTest.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigServiceTest.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigTest.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyEventTest.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyExperimentTest.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyFeatureTest.java

-  Audiences Implementation
-  Audience Support added in OptimizelyConfigService
-  Modification of Experiments to support serialize functionality from Conditions
-  Attributes and Events added to OptimizelyConfig
-  Cleanup of parsing functions to reuse code
-  Additional test cases added
-  Add Deprecation for OptimizelyFeature.experimentsMap
-  FSC
- "OASIS-7813"

Audiences, Attributes and Events implementation

---

core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyFeature.java

- Addition of deprecated warning for OptimizelyFeature.getExperimentsMap()
This function and member of OptimizelyFeature should no longer be used.
ExperimentRules and DeliveryRules including their getters are to be used in its place.
- FSC and IDE verification of Deprecation
- N/A

Update deprecated warning to OptimizelyFeature, getExperimentsMap().

---

.travis.yml
build.gradle

- travis support for releasing snapshot version for android test

chore: add snapshot publish to travis

---

core-api/src/main/java/com/optimizely/ab/config/PollingProjectConfigManager.java

- When datafile is parsed first time, it returns "null" for the previous version. The log message with "null previous version" can be confusing. Clean it up.
- "OASIS-7388"

chore: clean up datafile version log message

---

CHANGELOG.md

- 3.8.1 release note misses a bug fix for empty rollout cases.
- "OASIS-7997"

chore: add a missing bug-fix note

---

core-api/src/main/java/com/optimizely/ab/OptimizelyUserContext.java
core-api/src/test/java/com/optimizely/ab/OptimizelyUserContextTest.java

- Remove config-ready check from forced-decision apis
- Unit and FSC tests

fix(ForcedDecision): remove config-ready check from forced-decision apis

---

core-api/src/main/java/com/optimizely/ab/OptimizelyDecisionContext.java

- Add null check to OptimizelyDecisionContext constructor for flagKey
We want to confirm the user is not passing a null value as flagKey in addition to the @NonNull annotation provided to ensure the object is valid
- FSC
N/A

fix:update OptimizelyDecisionContext to check null for flagKey

---

java-quickstart/src/main/resources/log4j.properties

- Removing log4j properties from quick start application for now.
All fsc and unit tests should pass.

Update: Removed log4j properties from quick start application

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/OptimizelyUserContext.java
core-api/src/main/java/com/optimizely/ab/bucketing/DecisionService.java
core-api/src/main/java/com/optimizely/ab/config/DatafileProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfig.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/OptimizelyUserContextTest.java
core-api/src/test/java/com/optimizely/ab/bucketing/DecisionServiceTest.java

-  Moves findValidatedForcedDecision method to decision service as validatedForcedDecision
All unit test and FSC tests should pass.

move validate forced decision to decision service

---

README.md

Jcenter removed the deadline for old SDK versions.

chore: remove Jcenter deadline for old SDK versions

---

core-api/src/main/java/com/optimizely/ab/notification/NotificationManager.java
core-api/src/test/java/com/optimizely/ab/notification/NotificationManagerTest.java

- Fix NotificationManager to be thread-safe (add-handler and send-notifications can happen concurrently)
- Add a unit test concurrently adding handlers and sending notifications.
- OASIS-8135

fix(NotificationManager): add thread-safety to NotificationManager

---

build.gradle
core-httpclient-impl/build.gradle
core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyHttpClientTest.java

- http-httpclient module is not covered by travis (gradlew exhaustiveTest), which has been fixed.
- Fix a proxy testing not covered by travis.
- Upgrade jacoco to support Java 11

chore: fix http-httpclient module tests not included in travis

---

java-quickstart/gradle/wrapper/gradle-wrapper.properties
java-quickstart/settings.gradle

- remove the redundant settings.gradle from quickstart (it makes build failed with Intellij 2021.3)
- upgrade gradle to 6.5 for quickstart

chore: remove the redundant settings.gradle from quickstart

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/event/internal/BuildVersionInfo.java
core-api/src/main/java/com/optimizely/ab/event/internal/EventFactory.java
core-api/src/main/java/com/optimizely/ab/event/internal/payload/EventBatch.java
core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java
core-api/src/test/java/com/optimizely/ab/event/internal/EventFactoryTest.java

- Add an option to specify client-engine version (android-sdk, etc) in the Optimizely builder.
- Add a unit test for builder with client-engine version.
- OASIS-8188

fix: add Optimizely builder option for client-engine info

---

CHANGELOG.md

chore: prepare for release 3.10.2

---

core-api/src/main/java/com/optimizely/ab/internal/Cache.java
core-api/src/main/java/com/optimizely/ab/internal/DefaultLRUCache.java
core-api/src/main/java/com/optimizely/ab/internal/LRUCache.java
core-api/src/test/java/com/optimizely/ab/internal/DefaultLRUCacheTest.java

Added an interface for a generic LRUCache and a default Implementation.
- All existing tests pass.
- Added unit tests for the default cache implementation.
[OASIS-8385](https://optimizely.atlassian.net/browse/OASIS-8385)

feat: Added a generic LRUCache interface and a default implementation

---

core-api/src/main/java/com/optimizely/ab/config/DatafileProjectConfig.java
core-api/src/main/java/com/optimizely/ab/config/audience/AndCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/Audience.java
core-api/src/main/java/com/optimizely/ab/config/audience/AudienceIdCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/Condition.java
core-api/src/main/java/com/optimizely/ab/config/audience/EmptyCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/LeafCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/NotCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/NullCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/OrCondition.java
core-api/src/main/java/com/optimizely/ab/config/audience/UserAttribute.java
core-api/src/test/java/com/optimizely/ab/config/audience/AudienceConditionEvaluationTest.java

ODP Server needs a subset of segments to look for in the API call. This PR adds functionality to get all segments used in the project inside `DatafileProjectConfig`.
- Manually tested thoroughly
- Added Unit tests
[OASIS-8383](https://optimizely.atlassian.net/browse/OASIS-8383)

feat: Added support to get All segments used in the project

---

core-api/src/main/java/com/optimizely/ab/odp/ODPConfig.java
core-api/src/main/java/com/optimizely/ab/odp/ODPSegmentManager.java
core-api/src/main/java/com/optimizely/ab/odp/ODPSegmentOption.java
core-api/src/main/java/com/optimizely/ab/odp/ODPUserKey.java
core-api/src/test/java/com/optimizely/ab/odp/ODPSegmentManagerTest.java

Added an ODPSegmentManager which provides functionality to fetch segments from ODP server and cache and re-use them. 
- Manually tested thoroughly
- Added new unit tests
- Existing unit tests pass
- All Full stack compatibility suite tests pass
[OASIS-8383](https://optimizely.atlassian.net/browse/OASIS-8383)

feat: Added ODPSegmentManager

---

core-api/src/main/java/com/optimizely/ab/odp/ODPEvent.java
core-api/src/main/java/com/optimizely/ab/odp/ODPEventManager.java
core-api/src/test/java/com/optimizely/ab/odp/ODPEventManagerTest.java

Added `ODPEventManager` implementation.
- Unit tests pending.
[OASIS-8386](https://optimizely.atlassian.net/browse/OASIS-8386)

feat: Added ODPEventManager implementation

---

.github/workflows/java.yml

Fix github workflow to skip testing for SNAPSHOT and publish tasks.
- FSSDK-0000

chore: skip unit and fsc tests for snapshot and publish

---

core-httpclient-impl/src/main/java/com/optimizely/ab/HttpClientUtils.java
core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyHttpClient.java
core-httpclient-impl/src/main/java/com/optimizely/ab/odp/DefaultODPApiManager.java
core-httpclient-impl/src/test/java/com/optimizely/ab/odp/DefaultODPApiManagerTest.java

Added configurable timeouts for fetchSegments and dispatch events ODP calls. The default timeout is 10s.
- Manually tested thoroughly
- All test pass
[FSSDK-8689](https://jira.sso.episerver.net/browse/FSSDK-8689)

feat: Added configurable timeouts for fetchSegments and dispatch events ODP calls

---

core-api/src/main/java/com/optimizely/ab/internal/JsonParserProvider.java
core-api/src/main/java/com/optimizely/ab/odp/ODPEventManager.java
core-api/src/main/java/com/optimizely/ab/odp/parser/ResponseJsonParserFactory.java
core-api/src/test/java/com/optimizely/ab/odp/ODPEventManagerTest.java

1. Changed default event type from `client_initialized` to `identified`.
2. Changed Parser log levels from `info` to `debug`.
- Manually tested thoroughly.
- All existing unit tests and FSC test pass.
https://jira.sso.episerver.net/browse/FSSDK-8725
https://jira.sso.episerver.net/browse/FSSDK-8726

fix: Fixed ODP Event type and Json Parser log levels

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/OptimizelyUserContext.java
core-api/src/test/java/com/optimizely/ab/OptimizelyUserContextTest.java

`getQualifiedSegments` always returns empty list when fetch fails. Modified it to return null in case of failure. It will make it easy to differentiate between a fetch failure and a legit empty list response from the backed.
All existing tests pass
[FSSDK-8728](https://jira.sso.episerver.net/browse/FSSDK-8728)

fix: ODP - getQualifiedSegments should return null when fetch fails

---

core-api/src/main/java/com/optimizely/ab/odp/ODPEventManager.java

The ODP Event Dispatcher thread was not terminating with the application unless closed explicitly. Converted the thread to a daemon so that it stops when the main app exits.
- Manually tested thoroughly
- All existing tests pass
[FSSDK-8727](https://jira.sso.episerver.net/browse/FSSDK-8727)

fix: Made ODP Event Dispatcher thread a daemon

---

core-api/src/main/java/com/optimizely/ab/OptimizelyUserContext.java
core-api/src/main/java/com/optimizely/ab/odp/ODPEvent.java
core-api/src/main/java/com/optimizely/ab/odp/ODPEventManager.java
core-api/src/main/java/com/optimizely/ab/odp/ODPManager.java
core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyFeature.java
core-api/src/test/java/com/optimizely/ab/OptimizelyBuilderTest.java
core-api/src/test/java/com/optimizely/ab/odp/ODPEventManagerTest.java
core-api/src/test/java/com/optimizely/ab/odp/ODPManagerBuilderTest.java

Add support for Android-SDK ODP integration, which may not be implemented in the Android-SDK.
1. ODPManager.Builder.withExtraCommonData(commonData)
- clients (android-sdk) will pass common data (client os, device type,...) which should be added into all ODPEvents.
2. ODPManager.Builder.withExtraCommonIdentifiers(commonIdentifiers)
- clients (android-sdk) will pass common identifiers (vuid,...) which should be added into all ODPEvents.
Unit tests covering builder interface and generated events.
- FSSDK-8768

feat(ats): add support for android ODP events

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/config/AtomicProjectConfigManager.java
core-api/src/main/java/com/optimizely/ab/config/PollingProjectConfigManager.java
core-api/src/main/java/com/optimizely/ab/config/ProjectConfigManager.java
core-api/src/main/java/com/optimizely/ab/internal/NotificationRegistry.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/config/PollingProjectConfigManagerTest.java
core-api/src/test/java/com/optimizely/ab/internal/NotificationRegistryTest.java
core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyFactory.java
core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java
core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyFactoryTest.java
core-httpclient-impl/src/test/java/com/optimizely/ab/config/HttpProjectConfigManagerTest.java

- NotificationRegistry is added to create default NotificationCenter for internal use for updating ODPConfigSetting. 
- This is to handle a corner case that if in any case user passes different notificationCenter to Optimizely and ProjectconfigManager then the Notification of UpdateProjectConfig will not trigger because its handler is getting added in the main NotificationCenter object. 
- This will make sure UpdateProjectConfig will update ODPConfigSetting everytime irrespective of different NotificationCenter passed by user.
- Added getCachedConfig method in ProjectconfigManager to return ProjectConfig without await. 
**NOTE: breaking change**
Anyone who is implementing custom ProjectConfigManager should now have to implement `getCachedConfig` and `getSdkKey `. 
- Added additional unit …

Fix: Added notificationRegistry to make sure that odpSettings updates

---

core-api/src/main/java/com/optimizely/ab/odp/ODPApiManager.java
core-api/src/main/java/com/optimizely/ab/odp/ODPEventManager.java
core-api/src/main/java/com/optimizely/ab/odp/ODPSegmentManager.java
core-api/src/test/java/com/optimizely/ab/odp/ODPManagerTest.java
core-api/src/test/java/com/optimizely/ab/odp/ODPSegmentManagerTest.java
core-httpclient-impl/src/main/java/com/optimizely/ab/odp/DefaultODPApiManager.java
core-httpclient-impl/src/test/java/com/optimizely/ab/odp/DefaultODPApiManagerTest.java

- Refactored code of ODPAPIManager fetchQualifiedSegments  function to return list of qualifiedSegments. This is to keep it consistent with other SDKs
- This allows user to override the function and return the qualifiedSegment and they won't have to figure out how to parse the graphql response. 
Fixed some unit tests according to this new change. All unit tests should pass. 
- [FSSDK-8842](https://jira.sso.episerver.net/browse/FSSDK-8842)

Refact: ODPAPIManager now returns fetchQualifiedSegments list instead of string

---

core-api/src/main/java/com/optimizely/ab/odp/ODPEventManager.java
core-api/src/main/java/com/optimizely/ab/odp/ODPManager.java
core-api/src/main/java/com/optimizely/ab/odp/ODPSegmentManager.java
core-api/src/test/java/com/optimizely/ab/odp/ODPEventManagerTest.java
core-api/src/test/java/com/optimizely/ab/odp/ODPManagerTest.java
core-api/src/test/java/com/optimizely/ab/odp/ODPSegmentManagerTest.java

When vuid is used as userId, graphQL fetch segments api should be called with "vuid" as a query identifier.
- Unit test validating "vuid" as a query identifier.
- [FSSDK-8383](https://jira.sso.episerver.net/browse/FSSDK-8383)

fix(ats): convert graphQL query for fetchQualifiedSegments with vuid

---

README.md
build.gradle
core-api/README.md

Update all non-code-path SDK resources for Feature Experimenation
- Pass all tests
- [FSSDK-8953](https://jira.sso.episerver.net/browse/FSSDK-8953)

[FSSDK-8953] update non-code-path resources for FX

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/odp/ODPEvent.java
core-api/src/main/java/com/optimizely/ab/odp/ODPEventManager.java
core-api/src/main/java/com/optimizely/ab/odp/ODPUserKey.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/odp/ODPEventManagerTest.java

- Validate sendOdpEvent empty action and type parameters
- Generate new idempotence_id for every OdpEvent
added tests and all tests should pass.
[FSSDK-9076](https://jira.sso.episerver.net/browse/FSSDK-9076)

[FSSDK-9076] fix: send odp event empty values

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/OptimizelyUserContextTest.java

- Add check for ProjectConfig in odp methods.
This will ensure the datafile has been fetched first.
all tests pass
[FSSDK-9056](https://jira.sso.episerver.net/browse/FSSDK-9056)

[FSSDK-9056] fix: add config check in odp methods

---

core-api/src/main/java/com/optimizely/ab/odp/parser/impl/GsonParser.java
core-api/src/main/java/com/optimizely/ab/odp/parser/impl/JacksonParser.java
core-api/src/main/java/com/optimizely/ab/odp/parser/impl/JsonParser.java
core-api/src/main/java/com/optimizely/ab/odp/parser/impl/JsonSimpleParser.java
core-api/src/test/java/com/optimizely/ab/odp/parser/ResponseJsonParserTest.java
core-httpclient-impl/src/main/java/com/optimizely/ab/odp/DefaultODPApiManager.java

Support a new format for ODP `InvalidIdentifierException` (when SDK fetches segments with a non-registered userId).
```
"extensions": {
"code": "INVALID_IDENTIFIER_EXCEPTION",
"classification": "DataFetchingException"
}
```
- updated unit tests to cover the new response format.
- Existing unit tests should pass
- FSC should continue to pass
- FSSDK-9127

[FSSDK-9127] fix: Handle ODP INVALID_IDENTIFIER_EXCEPTION code

---

CHANGELOG.md

- Preparing for 4.0.0-beta pre release
- [FSSDK-8795](https://jira.sso.episerver.net/browse/FSSDK-8795)

[FSSDK-8795]chore: prepare for pre release 4.0.0-beta

---

.github/workflows/build.yml

ubuntu-18.04 not supported any more. upgrade it to latest.
- FSSDK-123

chore: fix ubuntu version for github actions

---

core-httpclient-impl/gradle.properties
gradle.properties
java-quickstart/build.gradle

Upgrade dependency versions to clear source clear warnings
- gson: 2.8.6 -> 2.10.1
- HttpClient: 4.5.13 -> 4.5.14
- Jackson-annotations: 2.11.2 -> 2.15.2
- pass all existing tests
- FSSDK-9041

[FSSDK-9041] chore: upgrade dependency versions

---

core-api/src/main/java/com/optimizely/ab/odp/ODPSegmentManager.java
core-api/src/test/java/com/optimizely/ab/OptimizelyUserContextTest.java

- This is to support other SDKs which are passing vuid as userid in async fetch qualified call
- Added unit test and all other tests should pass.
- [FSSDK-9493](https://jira.sso.episerver.net/browse/FSSDK-9493)

[FSSDK-9493] fix: Added check in AsyncGetQualifiedSegments to check if userID is fsuserid or vuid

---

core-api/src/main/java/com/optimizely/ab/config/PollingProjectConfigManager.java
core-api/src/test/java/com/optimizely/ab/config/PollingProjectConfigManagerTest.java

-  Implements a warning log for polling interval less than 30s
- [FSSDK-8739](https://jira.sso.episerver.net/browse/FSSDK-8739)

[FSSDK-8739] refact: Implements a warning log for polling interval less than 30s

---

core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java

- Added override close method in HttpProjectConfigManager to close httpClient
All tests should pass
- [FSSDK-9559](https://jira.sso.episerver.net/browse/FSSDK-9559)

[FSSDK-9559] Fix: Thread leak from httpClient in HttpProjectConfigManager

---

gradle.properties
java-quickstart/build.gradle
java-quickstart/src/main/resources/log4j2.properties

Add log4j2 dependencies and lo4j2.properties for log-level control in Example app.
Pass existing tests
- FSSDK-8110

[FSSDK-8110] chore: add sample log4j config to demo app

---

core-api/src/main/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigService.java
core-api/src/test/java/com/optimizely/ab/optimizelyconfig/OptimizelyConfigServiceTest.java
java-quickstart/src/main/java/com/optimizely/Example.java

When duplicate experiment keys are found in a datafile, SDK returns a correct experimentMap in OptimizelyConfig:
1. the experimentMap will contain the experiment later in the datafile experiments list.
2. add a warning log about "Duplicate experiment keys found in datafile: {key-name}"
- add a test for OptimizelyConfig with duplicate experiment keys
- [FSSDK-9785](https://jira.sso.episerver.net/browse/FSSDK-9785)

[FSSDK-9785] handle duplicate experiment keys with a warning

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/config/PollingProjectConfigManager.java
core-api/src/main/java/com/optimizely/ab/event/BatchEventProcessor.java
core-api/src/main/java/com/optimizely/ab/internal/DefaultLRUCache.java
core-api/src/main/java/com/optimizely/ab/notification/NotificationManager.java
core-api/src/main/java/com/optimizely/ab/odp/ODPConfig.java
core-api/src/main/java/com/optimizely/ab/odp/ODPEventManager.java
core-httpclient-impl/src/main/java/com/optimizely/ab/NamedThreadFactory.java
core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java
core-httpclient-impl/src/main/java/com/optimizely/ab/event/AsyncEventHandler.java

* In scope of this ticket I removed synchronized blocks as they pin virtual thread to carrier thread.
* Expose user way to inject ThreadFactory for creating virtual threads
- Fixes #537

Align to use virtual threads

---

build.gradle
core-api/src/test/java/com/optimizely/ab/odp/ODPEventManagerTest.java
core-httpclient-impl/README.md
core-httpclient-impl/build.gradle
core-httpclient-impl/src/main/java/com/optimizely/ab/HttpClientUtils.java
core-httpclient-impl/src/main/java/com/optimizely/ab/OptimizelyHttpClient.java
core-httpclient-impl/src/main/java/com/optimizely/ab/event/AsyncEventHandler.java
core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyHttpClientTest.java
core-httpclient-impl/src/test/java/com/optimizely/ab/event/AsyncEventHandlerTest.java

Events can be discarded for staled connections with httpclient connection pooling.
This PR fixs it with -
1. reduce the time for connection validation from 5 to 1sec.
2. enable retries (x3) for event POST.
- new unit tests covering parameter configurations and retries
- [FSSDK-10095](https://jira.sso.episerver.net/browse/FSSDK-10095)
- [BUG-7238](https://jira.sso.episerver.net/browse/BUG-7238)

[FSSDK-10095] fix events dropped on staled connections.

---

.github/workflows/build.yml
.github/workflows/integration_test.yml
.github/workflows/java.yml
README.md

-  Remove travis from doc
- [FSSDK-11075](https://jira.sso.episerver.net/browse/FSSDK-11075)

[FSSDK-11075] chore: remove travis from doc

---

.github/workflows/build.yml
.github/workflows/integration_test.yml
.github/workflows/java.yml
README.md

- The "what"; a concise description of each logical change
- Another change
- FSSDK-11075

[FSSDK-11075] chore: update github tag

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/test/java/com/optimizely/ab/OptimizelyTest.java
core-api/src/test/java/com/optimizely/ab/config/ValidProjectConfigV4.java

- Failed to convert big integer variable
- Replicate the external PR internally https://github.com/optimizely/java-sdk/pull/555
- All previous test cases should be passed
- [Issue](https://github.com/optimizely/java-sdk/issues/554)
- [FSSDK-11082](https://jira.sso.episerver.net/browse/FSSDK-11082)

[FSSDK-11082] fix: big integer conversion issue

---

.github/workflows/java.yml
README.md
build.gradle
core-httpclient-impl/build.gradle
core-httpclient-impl/src/main/java/com/optimizely/ab/config/HttpProjectConfigManager.java

Upgrade spotbugs from 4.1.1 to 4.9.5 (Prisma SCA)
- "FSSDK-1135"

[FSSDK-1135] upgrade spotbugs to 4.8.5

---

core-api/src/main/java/com/optimizely/ab/Optimizely.java
core-api/src/main/java/com/optimizely/ab/notification/DecisionNotification.java
core-api/src/test/java/com/optimizely/ab/OptimizelyUserContextTest.java
core-api/src/test/java/com/optimizely/ab/notification/DecisionNotificationTest.java

- Added `experimentId` and `variationId` to decision notification
- [FSSDK-11448](https://jira.sso.episerver.net/browse/FSSDK-11448)

[FSSDK-11448] Java Implementation: Add Experiment ID and Variation ID to Decision Notification

---

core-api/src/main/java/com/optimizely/ab/config/Cmab.java
core-api/src/main/java/com/optimizely/ab/config/Experiment.java
core-api/src/main/java/com/optimizely/ab/config/Group.java
core-api/src/main/java/com/optimizely/ab/config/parser/GsonHelpers.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonConfigParser.java
core-api/src/main/java/com/optimizely/ab/config/parser/JsonSimpleConfigParser.java
core-api/src/test/java/com/optimizely/ab/cmab/CmabTest.java
core-api/src/test/java/com/optimizely/ab/cmab/parser/CmabParsingTest.java
core-api/src/test/resources/config/cmab-config.json

Add cmab experiment properties to project config
- added unit test for cmab field
[FSSDK-11134](https://jira.sso.episerver.net/browse/FSSDK-11134)

[FSSDK-11134] Update: enable project config to track CMAB properties
